# This file contains the fastlane.tools configuration
# You can find the documentation on https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:ios)

platform :ios do
  desc "Run all unit tests for ImagineEngine (best engine)"
  lane :tests do
    run_tests(scheme: "ImagineEngine-iOS")
    run_tests(scheme: "ImagineEngine-macOS")
    run_tests(scheme: "ImagineEngine-tvOS")

    danger
  end
end
