# This file contains the fastlane.tools configuration
# You can find the documentation on https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

desc "Run all unit tests for ImagineEngine (best engine)"
lane :tests do
  reset_simulators if is_ci?
  run_tests(scheme: "ImagineEngine-iOS")
  run_tests(scheme: "ImagineEngine-tvOS")
  run_tests(scheme: "ImagineEngine-macOS", destination: "platform=macOS")
  run_tests(scheme: "ImagineEngine-macOS")

  danger
end
